### PR TITLE
Add cluster `expiration_timestamp`

### PR DESCRIPTION
**Pull request by jhernand**
This patch adds support for the new `expiration_timestamp` column of the
cluster type.

### CODE REVIEW

**Comment by jhernand** [comment]
@vkareh this replaces #53. Please review.

**Review by vkareh — APPROVED** [review]

**Comment by vkareh** [comment]
I'll go ahead and update the db column, thanks

**Comment by vkareh** [comment]
Database column rename sent to `clusters-service`. Once that's merged, this can be merged, then I can update the `uhc-sdk-go` revision hash on the `clusters-cleaner` and send it in.

**Pull request merged**
