### PR TITLE
Expose request path and method

### PR DESCRIPTION
**Pull request by tzvatot**
These functions can be used to extend the client.Request() adding a SendContext() function that can also log the request path and method, including the context (which can contain request ID).

@jhernand @zgalor PTAL

### CODE REVIEW

**Comment by cben** [comment]
LGTM.
Could also rename the fields Public.

**Comment by zgalor** [comment]
If we want this idiomatic `golang` - `path` and `method` should be public. This would also remove some existing code...

**Comment by tzvatot** [comment]
@cben @zgalor I can't rename `path` to public because there'a already a function called `Path` (which is actually a set-and-return).
I can change `method` to be public but that may be inconsistent with the `path` pattern (and may accidentally lead to someone trying to set the Method?).

**Comment by zgalor** [comment]
@tzvatot I think the `Path` method should be removed.
However, this is not backward compatible, so should consult with @jhernand regarding that

**Pull request merged**
